### PR TITLE
Change generic class type to wildcard i.e. support polymorphism

### PR DESCRIPTION
**Pull request by todoooo**
For a more flexible polymorphic design it is preferable to do this

  MyClass myInstance;

  Dao<Object, Integer> dao = getHelper().getDao(myInstance.getClass());
  dao.update(myInstance);

than use a hard-code class type like this

  MyClass myInstance;

  Dao<MyClass, Integer> dao = getHelper().getDao(MyClass.class);
  dao.update(myInstance);

The proposed change set allows this.

### CODE REVIEW

**Comment by j256** [comment]
I still don't understand why this is necessary.  When does the Dao<T, ID> not match the Class<T> being asked for.

**Comment by j256** [comment]
And can't you handle this with a cast if you are doing something funky?

**Comment by todoooo** [comment]
An example might help.

Let's say I have a number of persistent objects in my model which are held in a List<Object>, so I can only determine each item's class by item.getClass(). When an item is edited I need to save it by doing
Dao dao = getHelper().getDao(item.getClass());
dao.update(item);

Currently that is not possible.

**Comment by j256** [comment]
Thanks for the update.

**Comment by j256** [comment]
Sorry, this is old but I still don't understand.  You can't use a DAO for multiple types. The DAO has specific information tied to a specific class.  I think I'm still not understanding how your change adds anything.

**Comment by todoooo** [comment]
> 
> 
> Sorry, this is old but I still don't understand. You can't use a DAO for multiple types. The DAO has specific information tied to a specific class. I think I'm still not understanding how your change adds anything.

Yes. Each DAO is specific to a class. The point of the change is to "select" the right DAO at runtime based on the item class. 
If you hard-code the class for saving an object then you have to edit/change all the code when new derived classes are added to your model. Think of a list of items inheriting from the same base class, but having different concrete implementations. (i.e. polymorphism). Your current design is not dynamic.

**Comment by j256** [comment]
Aha!  Yeah polymorphism is on the list but it's _hard_.  I should sit down and take a serious whack at it but it's going to be a _huge_ change.  But thanks for the poke.

**Comment by todoooo** [comment]
The change set I pushed handles polymorphism using your existing code. It also doesn't break backward compatibility for hard-coded access to the DAOs. After 4 years it still merges without conflicts which is incredible. Try it!

**Comment by j256** [comment]
You've not changed anything but the generic signatures.  I still don't understand why this buys you anything.  If I have a `fooDao` then I _want_ it to be a `Dao<Foo, Integer>` and not a `Dao<?, ?>`.  I don't want to make mistakes and cast it to a `Dao<Bar, Long>` by accident.  Any casting that I do is going to need warnings suppressed right?

Sorry if I'm just not getting it.  Can you send me a unit test or a small code sample that shows this in operation?

**Comment by ndawod** [comment]
This looks like something I wouldn't want in my code. It's like coding with a strictly-typed language versus a non strictly-typed language.

In my humble opinion, this may open a can of worms...

**Comment by todoooo** [comment]
The wildcards allow you to specify an abstract base class in the variable declaration.

Foo myInstance;

Dao<BaseFoo, Integer> dao = getHelper().getDao(myInstance.getClass());
dao.update(myInstance);

Perhaps ? extends T would be better, but I don't think java supports that syntax.

**Comment by todoooo** [comment]
Well I just looked up Java generic wild cards and I see there is both `? extends T` and `? super T`

So it should be possible to achieve dynamic access to DAOs without sacrificing compiler type checking. I haven't looked at your ORM code for years, but I seem to recall getting compiler errors with

`public synchronized static <D extends Dao<? extends T, ?>, T> D lookupDao(ConnectionSource	connectionSource, Class<? extends T> clazz)`

when I probably should have converted this
`public synchronized static <D extends Dao<T, ?>, T> D createDao(ConnectionSource connectionSource, Class<T> clazz)`

to this
`public synchronized static <D extends Dao<T, ?>, ? extends T> D lookupDao(ConnectionSource	connectionSource, Class<? extends T> clazz)`

or this
`public synchronized static <D extends Dao<T, ?>, ? super T> D lookupDao(ConnectionSource	connectionSource, Class<? super T> clazz)`

**Comment by j256** [comment]
Sorry dude.  I don't think this takes functionality away from the library.  You should be able to do your own casting however feel free.

**Comment by todoooo** [comment]
You can't cast away dependence on a hard-coded type specification in the code.

**Pull request closed without merging**
