### PR TITLE
Doc lint compliance java8

### PR DESCRIPTION
**Pull request by VincentFTS**
Compiling with Java 8 requires to be DocLint compliant.

### CODE REVIEW

**Comment by j256** [comment]
I'm not gong to take this push because I don't agree with the <p> tuning, but I've fixed a number of places with < and > in the javadocs and I've added exclusions for the Java 8 methods.   See: https://github.com/j256/ormlite-core/commit/1e5b83a7b4164a1be52a8398c689a0e0b6ae2d9b

Thanks.

**Comment by VincentFTS** [comment]
Hi @j256 ,

I've just moved from my branch to your master branch, and I still get errors when building with Java 8. Do you build with Java8 or Java7 ? Here is a little explanation of Java 8 doclint requirements http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html

**Comment by j256** [comment]
I compile with Java 6.  Is there any way to turn off the doclint requirements?   At the bottom of that page you posted is how to turn it off.  Does that work?

**Comment by j256** [comment]
Hey @VincentFTS, do I have your email address?  Can you contact me: http://256.com/gray/email/

**Comment by j256** [comment]
This was taken care of interactively.

**Pull request closed without merging**
