### PR TITLE
Remove some synthetic accessors.

### PR DESCRIPTION
**Pull request by Miha-x64**
For more info watch https://realm.io/news/360andev-jake-wharton-java-hidden-costs-android/

### CODE REVIEW

**Comment by j256** [comment]
Why make those package as opposed to protected?  What access is needed there that isn't a subclass?

**Comment by Miha-x64** [comment]
Technically, inner class can't access outer class's private members and vice versa, so javac generates synthetic package-private accessor methods that allow this.
I've changed access modifiers not to subclass but to reduce methods count, that can be critical in Android.

In IDEA, you can easily see these cases of access:
access inspection

**Comment by j256** [comment]
Wow.  I'm surprised I didn't know that.  Makes complete sense.   And I can't believe I missed some finals.  I'm usually good about that.  Thanks much.

**Comment by j256** [comment]
Hrm.  Any idea how can I detect synthetic methods to watch out for them?  I'm surprised that there aren't tools or plugins.  Or maybe my google searches are just failing.

**Comment by Miha-x64** [comment]
Watch a screenshot above, IntelliJ IDEA / Android Studio helps me in finding this out.
Also there are many useful inspection that can help noticing possible performance and memory issues.

**Pull request merged**
