### PR TITLE
Add support for java.util.Currency

### PR DESCRIPTION
**Pull request by juur**

### CODE REVIEW

**Comment by noordawod** [comment]
LGTM

**Comment by j256** [comment]
Do we want to add a auto-detect to the DataType class?  Any reason not to?

Also, can this be reformatted to match the other code?  If not then I can do it after we take it.

**Comment by j256** [comment]
To fix the Eclipse behavior, Preferences -> Java -> Editor -> Save Actions -> uncheck "Format source code".

**Comment by j256** [comment]
Sorry for the delay on this.

**Pull request merged**
