### PR TITLE
unregister all DAOs by a connection source to clear memory

### PR DESCRIPTION
**Pull request by bosborn**

### CODE REVIEW

**Comment by j256** [comment]
Interesting.  I like the idea but I'm not sure about the map of sets.  How about just iterating through the map and finding all of the connection sources that match.  Do we really think we are going to have 1000s of DOAs that would make that inefficient?

**Comment by bosborn** [comment]
Changed to remove a connection source cache through iteration.  Performance takes the small hit when large numbers of connections and/or DAOs have been cached, but code complexity is largely reduced.

The connection source unregister method could be called upon closing a connection source to automatically clear that memory.  Right now it looks like that would require adding the call to each connection source implementation.

**Comment by noordawod** [comment]
This looks sane to me, @j256.

**Comment by j256** [comment]
Agreed @noordawod .  Merged.  Thanks @bosborn .

**Pull request merged**
