### PR TITLE
Add LIMIT support to UpdateBuilder

### PR DESCRIPTION
**Pull request by juur**
Code borrowed from QueryBuilder. Have re-used isLimitAfterSelect() although in future may wish to have specific check for UPDATE and/or not bother.

### CODE REVIEW

**Comment by noordawod** [comment]
@j256 lgtm

**Comment by j256** [comment]
Thanks for this.  I think it needs some tweaks.  I'll move it up to the base class.  Next we need to see which database types support an update (or delete?) limit.  I'm on it.

**Comment by juur** [comment]
- **MariaDB/MySQL** is a **YES:** https://mariadb.com/kb/en/library/update/
- **SQLite** is **OPTIONAL:** https://www.sqlite.org/compile.html#enable_update_delete_limit. I don't know how to test other than doing something like `SELECT 1 LIMIT 1;` (which works for me on Centos7)
- **PostgreSQL** is a **NO:** https://dba.stackexchange.com/questions/69471/postgres-update-limit-1
- **HSQLDB** is a **YES:** http://hsqldb.org/doc/guide/dataaccess-chapt.html#dac_update_statement
- **Derby** is a **YES,** **BUT** _uses a different syntax:_ https://stackoverflow.com/questions/39298911/sql-error-while-using-limit-keyword-in-derby
- **H2** is a YES: http://www.h2database.com/html/grammar.html#update
- **Microsoft SQL** is a NO: Something can be approximated using TOP and ORDER BY, but I am not sure if it is really the same: https://docs.microsoft.com/en-us/sql/t-sql/queries/update-transact-sql?view=sql-server-2017#LimitingValues

**Comment by j256** [comment]
Wow @juur .  Great stuff!  I'm worried about the sqlite optional of course.  My instinct is to say no and allow folks to override with their own custom database type.  Or maybe add a setter or something.   Thoughts?

**Comment by juur** [comment]
Re: SQLite. I've had a quick Google and I can't see anyway of easily checking for compile time options. So I think you have three options: a) have a probe on first use that tries a simple LIMIT and traps the error (e.g. `SELECT 1 LIMIT 1`). b) have a settter/getter or c) use a global property.

**Comment by j256** [comment]
Thanks much @juur .

**Comment by juur** [comment]
Any progress here? Is there anything I can do?

**Comment by j256** [comment]
Sorry for the delay.  This took a lot more work than I would have thought.  Upgrading H2 to 1.4.200 exposed a bunch of issues and broke some internal support for things.

**Comment by j256** [comment]
Not sure why this is showing the `CurrencyPersister`.  Please copy that into a new pull request if still valid.

**Pull request closed without merging**
