### PR TITLE
 Move log4j logger to core (where all the other loggers are)

### PR DESCRIPTION
**Pull request by MarcMil**

### CODE REVIEW

**Comment by j256** [comment]
Why do this?  The entire point was to keep it out of the Android namespace.  Can Android use these?

**Comment by MarcMil** [comment]
Firstly, OSGI issues. There were classes of different projects/jars in the same package. OSGI/Eclipse plugins do not like this, and this prevents using Ormlite in this context. In the OSGI world, ormlite-jdbc and ormlite-core are separated plug-ins. Furthermore, because ormlite-core tries to load classes of ormlite-jdbc via Class.forName, there is a dependency at runtime to ormlite-jdbc. Since ormlite-jdbc has a dependency on ormlite-core as well, this makes it cyclic. OSGI prevents cyclic relationships and thus loading the log4j logger simply fails.

Even if currently log4j2 is currently unavailable on Android (which I don't know), there might be support in the future.
Secondly, it does not appear to be very clean from an software engineering standpoint to put all but one logger framework in to ormlite-core and one into ormlite-jdbc, just because Android can't use it. They are optional dependencies to begin with, and Android does not have to include or use them. The placement of a logger into the JDBC-project seems pretty random, as there is no relationship between JDBC and Loggers.
Since the available Loggers are determined at runtime via reflection anyway, there would be no harm in including log4j as optional dependency, just as slf4j and commons-logging.

**Comment by j256** [comment]
> Secondly, it does not appear to be very clean from an software engineering standpoint to put all but one logger framework in to ormlite-core and one into ormlite-jdbc, just because Android can't use it.

The issue with Android was (maybe not anymore) size of binary.  I didn't want to include stuff in core that they couldn't use.  That said, maybe we are in 2020 now and the apps are larger and maybe a couple classes doesn't matter.  I'll take a look again.

**Comment by MarcMil** [comment]
In case it is still a problem: We could also avoid the cyclic dependencies if there was a third project which just contains loggers (or a project for each logger-type, similar to slf4j). As the logger classes do (afaik) not need access to any ORMLite-specific types, there should no need for such a logger project to have any reference to ormlite-core, ormlite-jdbc or ormlite-android, right?

**Comment by j256** [comment]
Sorry this is spot on and I should have merged it.  Sorry.

**Pull request closed without merging**
