### PR TITLE
Another queryRaw method that let you use ResultSet object directly in mapper.

### PR DESCRIPTION
**Pull request by nonameplum**
This pull request can be used to close issue:
https://github.com/j256/ormlite-core/issues/15
and 
https://github.com/j256/ormlite-core/issues/14

### CODE REVIEW

**Comment by j256** [comment]
Yeah, this will fail to compile on Android since it doesn't have the ResultSet.  Is there some code we can add just to the JDBC side of the fence to achieve this?

**Comment by j256** [comment]
Ok, I can see the utility here but in ormlite-core, we can't deal with the ResultSet directly because that's JDBC specific.  I've merged the code by hand and made it a DatabaseResults mapper.  In JDBC land you can cast this to JdbcDatabaseResults which as a getResultSet() method on it.  A bit ugly but more in keeping with -core.  Thanks!   See: https://github.com/j256/ormlite-core/commit/2c2c66b2de850bfd97840068e2d46ac64d9b1869

**Comment by nonameplum** [comment]
Hi, it is good compromise. I changed my code to you DatabaseResults mapper and I'm happy so far.
You could also remove ResultSetMapper class totaly and clean up code.
Thanks.

**Comment by j256** [comment]
Glad it worked for you.  That stuff is in your branch.  I've merged it by hand so you can just remove the request.

**Pull request closed without merging**
